// The MIT License (MIT)
//
// Copyright (c) 2015 Johan Johansson
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

//! Enumerations used to specify information about shaders
//!
//! # References
//! [D3D11 Shader Enumerations, MSDN]
//! (https://msdn.microsoft.com/en-us/library/windows/desktop/ff476175(v=vs.85).aspx)

#![allow(non_camel_case_types)]

use common_version::enumerations::*;

pub type D3D11_CBUFFER_TYPE = D3D_CBUFFER_TYPE;
pub type D3D11_RESOURCE_RETURN_TYPE = D3D_RESOURCE_RETURN_TYPE;
pub type D3D11_TESSELLATOR_DOMAIN = D3D_TESSELLATOR_DOMAIN;
pub type D3D11_TESSELLATOR_PARTITIONING = D3D_TESSELLATOR_PARTITIONING;
pub type D3D11_TESSELLATOR_OUTPUT_PRIMITIVE = D3D_TESSELLATOR_OUTPUT_PRIMITIVE;

#[repr(C)] pub enum D3D_PARAMETER_FLAGS {
	NONE = 0x00000000,
	IN = 0x00000001,
	OUT = 0x00000002,
	FORCE_DWORD = 0x7fffffff
}
#[repr(C)] pub enum D3D11_SHADER_TYPE {
	VERTEX_SHADER = 1,
	HULL_SHADER = 2,
	DOMAIN_SHADER = 3,
	GEOMETRY_SHADER = 4,
	PIXEL_SHADER = 5,
	COMPUTE_SHADER = 6
}
#[repr(C)] pub enum D3D11_TRACE_GS_INPUT_PRIMITIVE {
	UNDEFINED = 0,
	POINT = 1,
	LINE = 2,
	TRIANGLE = 3,
	LINE_ADJ = 6,
	TRIANGLE_ADJ = 7
}
#[repr(C)] pub enum D3D11_TRACE_REGISTER_TYPE {
	OUTPUT_NULL_REGISTER = 0,
	INPUT_REGISTER,
	INPUT_PRIMITIVE_ID_REGISTER,
	IMMEDIATE_CONSTANT_BUFFER,
	TEMP_REGISTER,
	INDEXABLE_TEMP_REGISTER,
	OUTPUT_REGISTER,
	OUTPUT_DEPTH_REGISTER,
	CONSTANT_BUFFER,
	IMMEDIATE32,
	SAMPLER,
	RESOURCE,
	RASTERIZER,
	OUTPUT_COVERAGE_MASK,
	STREAM,
	THIS_POINTER,
	OUTPUT_CONTROL_POINT_ID_REGISTER,
	INPUT_FORK_INSTANCE_ID_REGISTER,
	INPUT_JOIN_INSTANCE_ID_REGISTER,
	INPUT_CONTROL_POINT_REGISTER,
	OUTPUT_CONTROL_POINT_REGISTER,
	INPUT_PATCH_CONSTANT_REGISTER,
	INPUT_DOMAIN_POINT_REGISTER,
	UNORDERED_ACCESS_VIEW,
	THREAD_GROUP_SHARED_MEMORY,
	INPUT_THREAD_ID_REGISTER,
	INPUT_THREAD_GROUP_ID_REGISTER,
	INPUT_THREAD_ID_IN_GROUP_REGISTER,
	INPUT_COVERAGE_MASK_REGISTER,
	INPUT_THREAD_ID_IN_GROUP_FLATTENED_REGISTER,
	INPUT_GS_INSTANCE_ID_REGISTER,
	OUTPUT_DEPTH_GREATER_EQUAL_REGISTER,
	OUTPUT_DEPTH_LESS_EQUAL_REGISTER,
	IMMEDIATE64,
	INPUT_CYCLE_COUNTER_REGISTER,
	INTERFACE_POINTER,
}
#[repr(C)] pub enum D3D11_SHADER_VERSION_TYPE {
	PIXEL_SHADER = 0,
	VERTEX_SHADER = 1,
	GEOMETRY_SHADER = 2,
	
	// D3D11 Shaders
	HULL_SHADER = 3,
	DOMAIN_SHADER = 4,
	COMPUTE_SHADER = 5,

	RESERVED0 = 0xFFF0,
}