//! Common Version Enumerations provided by D3D11
//!
//! # References
//! [D3D11 Common Version Enumerations, MSDN]
//! (https://msdn.microsoft.com/en-us/library/windows/desktop/ff728661(v=vs.85).aspx)

#[repr(C)]
pub enum D3D_CBUFFER_TYPE {
    CBUFFER = 0,
    TBUFFER = 1,
    INTERFACE_POINTERS = 2,
    RESOURCE_BIND_INFO = 3,
}
pub const D3D10_CT_CBUFFER: D3D_CBUFFER_TYPE = D3D_CBUFFER_TYPE::CBUFFER;
pub const D3D10_CT_TBUFFER: D3D_CBUFFER_TYPE = D3D_CBUFFER_TYPE::TBUFFER;
pub const D3D11_CT_CBUFFER: D3D_CBUFFER_TYPE = D3D_CBUFFER_TYPE::CBUFFER;
pub const D3D11_CT_TBUFFER: D3D_CBUFFER_TYPE = D3D_CBUFFER_TYPE::TBUFFER;
pub const D3D11_CT_INTERFACE_POINTERS: D3D_CBUFFER_TYPE = D3D_CBUFFER_TYPE::INTERFACE_POINTERS;
pub const D3D11_CT_RESOURCE_BIND_INFO: D3D_CBUFFER_TYPE = D3D_CBUFFER_TYPE::RESOURCE_BIND_INFO;

#[repr(C)]
pub enum D3D_DRIVER_TYPE {
    UNKNOWN = 0,
    HARDWARE = 2,
    REFERENCE = 3,
    NULL = 4,
    SOFTWARE = 5,
    WARP = 6,
}

#[repr(C)]
pub enum D3D_FEATURE_LEVEL {
    FL_9_1 = 0x9100,
    FL_9_2 = 0x9200,
    FL_9_3 = 0x9300,
    FL_10_0 = 0xa000,
    FL_10_1 = 0xa100,
    FL_11_0 = 0xb000,
    FL_11_1 = 0xb100,
}

#[repr(C)]
pub enum D3D_INCLUDE_TYPE {
    LOCAL = 0,
    SYSTEM = 1,
    FORCE_DWORD = 0x7fffffff,
}
pub const D3D10_INCLUDE_LOCAL: D3D_INCLUDE_TYPE = D3D_INCLUDE_TYPE::LOCAL;
pub const D3D10_INCLUDE_SYSTEM: D3D_INCLUDE_TYPE = D3D_INCLUDE_TYPE::SYSTEM;

#[repr(C)]
pub enum D3D_INTERPOLATION_MODE {
    UNDEFINED = 0,
    CONSTANT = 1,
    LINEAR = 2,
    LINEAR_CENTROID = 3,
    LINEAR_NOPERSPECTIVE = 4,
    LINEAR_NOPERSPECTIVE_CENTROID = 5,
    LINEAR_SAMPLE = 6,
    LINEAR_NOPERSPECTIVE_SAMPLE = 7,
}

#[repr(C)]
pub enum D3D_MIN_PRECISION {
    DEFAULT = 0,
    FLOAT_16 = 1,
    FLOAT_2_8 = 2,
    RESERVED = 3,
    SINT_16 = 4,
    UINT_16 = 5,
    ANY_16 = 0xf0,
    ANY_10 = 0xf1,
}

#[repr(C)]
pub enum D3D_NAME {
    UNDEFINED = 0,
    POSITION = 1,
    CLIP_DISTANCE = 2,
    CULL_DISTANCE = 3,
    RENDER_TARGET_ARRAY_INDEX = 4,
    VIEWPORT_ARRAY_INDEX = 5,
    VERTEX_ID = 6,
    PRIMITIVE_ID = 7,
    INSTANCE_ID = 8,
    IS_FRONT_FACE = 9,
    SAMPLE_INDEX = 10,
    FINAL_QUAD_EDGE_TESSFACTOR = 11,
    FINAL_QUAD_INSIDE_TESSFACTOR = 12,
    FINAL_TRI_EDGE_TESSFACTOR = 13,
    FINAL_TRI_INSIDE_TESSFACTOR = 14,
    FINAL_LINE_DETAIL_TESSFACTOR = 15,
    FINAL_LINE_DENSITY_TESSFACTOR = 16,
    TARGET = 64,
    DEPTH = 65,
    COVERAGE = 66,
    DEPTH_GREATER_EQUAL = 67,
    DEPTH_LESS_EQUAL = 68,
}
pub const D3D10_NAME_UNDEFINED: D3D_NAME = D3D_NAME::UNDEFINED;
pub const D3D10_NAME_POSITION: D3D_NAME = D3D_NAME::POSITION;
pub const D3D10_NAME_CLIP_DISTANCE: D3D_NAME = D3D_NAME::CLIP_DISTANCE;
pub const D3D10_NAME_CULL_DISTANCE: D3D_NAME = D3D_NAME::CULL_DISTANCE;
pub const D3D10_NAME_RENDER_TARGET_ARRAY_INDEX: D3D_NAME = D3D_NAME::RENDER_TARGET_ARRAY_INDEX;
pub const D3D10_NAME_VIEWPORT_ARRAY_INDEX: D3D_NAME = D3D_NAME::VIEWPORT_ARRAY_INDEX;
pub const D3D10_NAME_VERTEX_ID: D3D_NAME = D3D_NAME::VERTEX_ID;
pub const D3D10_NAME_PRIMITIVE_ID: D3D_NAME = D3D_NAME::PRIMITIVE_ID;
pub const D3D10_NAME_INSTANCE_ID: D3D_NAME = D3D_NAME::INSTANCE_ID;
pub const D3D10_NAME_IS_FRONT_FACE: D3D_NAME = D3D_NAME::IS_FRONT_FACE;
pub const D3D10_NAME_SAMPLE_INDEX: D3D_NAME = D3D_NAME::SAMPLE_INDEX;
pub const D3D10_NAME_TARGET: D3D_NAME = D3D_NAME::TARGET;
pub const D3D10_NAME_DEPTH: D3D_NAME = D3D_NAME::DEPTH;
pub const D3D10_NAME_COVERAGE: D3D_NAME = D3D_NAME::COVERAGE;
pub const D3D11_NAME_FINAL_QUAD_EDGE_TESSFACTOR: D3D_NAME = D3D_NAME::FINAL_QUAD_EDGE_TESSFACTOR;
pub const D3D11_NAME_FINAL_QUAD_INSIDE_TESSFACTOR: D3D_NAME =
    D3D_NAME::FINAL_QUAD_INSIDE_TESSFACTOR;
pub const D3D11_NAME_FINAL_TRI_EDGE_TESSFACTOR: D3D_NAME = D3D_NAME::FINAL_TRI_EDGE_TESSFACTOR;
pub const D3D11_NAME_FINAL_TRI_INSIDE_TESSFACTOR: D3D_NAME = D3D_NAME::FINAL_TRI_INSIDE_TESSFACTOR;
pub const D3D11_NAME_FINAL_LINE_DETAIL_TESSFACTOR: D3D_NAME =
    D3D_NAME::FINAL_LINE_DETAIL_TESSFACTOR;
pub const D3D11_NAME_FINAL_LINE_DENSITY_TESSFACTOR: D3D_NAME =
    D3D_NAME::FINAL_LINE_DENSITY_TESSFACTOR;
pub const D3D11_NAME_DEPTH_GREATER_EQUAL: D3D_NAME = D3D_NAME::DEPTH_GREATER_EQUAL;
pub const D3D11_NAME_DEPTH_LESS_EQUAL: D3D_NAME = D3D_NAME::DEPTH_LESS_EQUAL;

#[repr(C)]
pub enum D3D_PRIMITIVE {
    UNDEFINED = 0,
    POINT = 1,
    LINE = 2,
    TRIANGLE = 3,
    LINE_ADJ = 6,
    TRIANGLE_ADJ = 7,
    CONTROL_POINT_PATCH_1 = 8,
    CONTROL_POINT_PATCH_2 = 9,
    CONTROL_POINT_PATCH_3 = 10,
    CONTROL_POINT_PATCH_4 = 11,
    CONTROL_POINT_PATCH_5 = 12,
    CONTROL_POINT_PATCH_6 = 13,
    CONTROL_POINT_PATCH_7 = 14,
    CONTROL_POINT_PATCH_8 = 15,
    CONTROL_POINT_PATCH_9 = 16,
    CONTROL_POINT_PATCH_10 = 17,
    CONTROL_POINT_PATCH_11 = 18,
    CONTROL_POINT_PATCH_12 = 19,
    CONTROL_POINT_PATCH_13 = 20,
    CONTROL_POINT_PATCH_14 = 21,
    CONTROL_POINT_PATCH_15 = 22,
    CONTROL_POINT_PATCH_16 = 23,
    CONTROL_POINT_PATCH_17 = 24,
    CONTROL_POINT_PATCH_18 = 25,
    CONTROL_POINT_PATCH_19 = 26,
    CONTROL_POINT_PATCH_20 = 28,
    CONTROL_POINT_PATCH_21 = 29,
    CONTROL_POINT_PATCH_22 = 30,
    CONTROL_POINT_PATCH_23 = 31,
    CONTROL_POINT_PATCH_24 = 32,
    CONTROL_POINT_PATCH_25 = 33,
    CONTROL_POINT_PATCH_26 = 34,
    CONTROL_POINT_PATCH_27 = 35,
    CONTROL_POINT_PATCH_28 = 36,
    CONTROL_POINT_PATCH_29 = 37,
    CONTROL_POINT_PATCH_30 = 38,
    CONTROL_POINT_PATCH_31 = 39,
    CONTROL_POINT_PATCH_32 = 40,
}
pub const D3D10_PRIMITIVE_UNDEFINED: D3D_PRIMITIVE = D3D_PRIMITIVE::UNDEFINED;
pub const D3D10_PRIMITIVE_POINT: D3D_PRIMITIVE = D3D_PRIMITIVE::POINT;
pub const D3D10_PRIMITIVE_LINE: D3D_PRIMITIVE = D3D_PRIMITIVE::LINE;
pub const D3D10_PRIMITIVE_TRIANGLE: D3D_PRIMITIVE = D3D_PRIMITIVE::TRIANGLE;
pub const D3D10_PRIMITIVE_LINE_ADJ: D3D_PRIMITIVE = D3D_PRIMITIVE::LINE_ADJ;
pub const D3D10_PRIMITIVE_TRIANGLE_ADJ: D3D_PRIMITIVE = D3D_PRIMITIVE::TRIANGLE_ADJ;
pub const D3D11_PRIMITIVE_UNDEFINED: D3D_PRIMITIVE = D3D_PRIMITIVE::UNDEFINED;
pub const D3D11_PRIMITIVE_POINT: D3D_PRIMITIVE = D3D_PRIMITIVE::POINT;
pub const D3D11_PRIMITIVE_LINE: D3D_PRIMITIVE = D3D_PRIMITIVE::LINE;
pub const D3D11_PRIMITIVE_TRIANGLE: D3D_PRIMITIVE = D3D_PRIMITIVE::TRIANGLE;
pub const D3D11_PRIMITIVE_LINE_ADJ: D3D_PRIMITIVE = D3D_PRIMITIVE::LINE_ADJ;
pub const D3D11_PRIMITIVE_TRIANGLE_ADJ: D3D_PRIMITIVE = D3D_PRIMITIVE::TRIANGLE_ADJ;
pub const D3D11_PRIMITIVE_1_CONTROL_POINT_PATCH: D3D_PRIMITIVE =
    D3D_PRIMITIVE::CONTROL_POINT_PATCH_1;
pub const D3D11_PRIMITIVE_2_CONTROL_POINT_PATCH: D3D_PRIMITIVE =
    D3D_PRIMITIVE::CONTROL_POINT_PATCH_2;
pub const D3D11_PRIMITIVE_3_CONTROL_POINT_PATCH: D3D_PRIMITIVE =
    D3D_PRIMITIVE::CONTROL_POINT_PATCH_3;
pub const D3D11_PRIMITIVE_4_CONTROL_POINT_PATCH: D3D_PRIMITIVE =
    D3D_PRIMITIVE::CONTROL_POINT_PATCH_4;
pub const D3D11_PRIMITIVE_5_CONTROL_POINT_PATCH: D3D_PRIMITIVE =
    D3D_PRIMITIVE::CONTROL_POINT_PATCH_5;
pub const D3D11_PRIMITIVE_6_CONTROL_POINT_PATCH: D3D_PRIMITIVE =
    D3D_PRIMITIVE::CONTROL_POINT_PATCH_6;
pub const D3D11_PRIMITIVE_7_CONTROL_POINT_PATCH: D3D_PRIMITIVE =
    D3D_PRIMITIVE::CONTROL_POINT_PATCH_7;
pub const D3D11_PRIMITIVE_8_CONTROL_POINT_PATCH: D3D_PRIMITIVE =
    D3D_PRIMITIVE::CONTROL_POINT_PATCH_8;
pub const D3D11_PRIMITIVE_9_CONTROL_POINT_PATCH: D3D_PRIMITIVE =
    D3D_PRIMITIVE::CONTROL_POINT_PATCH_9;
pub const D3D11_PRIMITIVE_10_CONTROL_POINT_PATCH: D3D_PRIMITIVE =
    D3D_PRIMITIVE::CONTROL_POINT_PATCH_10;
pub const D3D11_PRIMITIVE_11_CONTROL_POINT_PATCH: D3D_PRIMITIVE =
    D3D_PRIMITIVE::CONTROL_POINT_PATCH_11;
pub const D3D11_PRIMITIVE_12_CONTROL_POINT_PATCH: D3D_PRIMITIVE =
    D3D_PRIMITIVE::CONTROL_POINT_PATCH_12;
pub const D3D11_PRIMITIVE_13_CONTROL_POINT_PATCH: D3D_PRIMITIVE =
    D3D_PRIMITIVE::CONTROL_POINT_PATCH_13;
pub const D3D11_PRIMITIVE_14_CONTROL_POINT_PATCH: D3D_PRIMITIVE =
    D3D_PRIMITIVE::CONTROL_POINT_PATCH_14;
pub const D3D11_PRIMITIVE_15_CONTROL_POINT_PATCH: D3D_PRIMITIVE =
    D3D_PRIMITIVE::CONTROL_POINT_PATCH_15;
pub const D3D11_PRIMITIVE_16_CONTROL_POINT_PATCH: D3D_PRIMITIVE =
    D3D_PRIMITIVE::CONTROL_POINT_PATCH_16;
pub const D3D11_PRIMITIVE_17_CONTROL_POINT_PATCH: D3D_PRIMITIVE =
    D3D_PRIMITIVE::CONTROL_POINT_PATCH_17;
pub const D3D11_PRIMITIVE_18_CONTROL_POINT_PATCH: D3D_PRIMITIVE =
    D3D_PRIMITIVE::CONTROL_POINT_PATCH_18;
pub const D3D11_PRIMITIVE_19_CONTROL_POINT_PATCH: D3D_PRIMITIVE =
    D3D_PRIMITIVE::CONTROL_POINT_PATCH_19;
pub const D3D11_PRIMITIVE_20_CONTROL_POINT_PATCH: D3D_PRIMITIVE =
    D3D_PRIMITIVE::CONTROL_POINT_PATCH_20;
pub const D3D11_PRIMITIVE_21_CONTROL_POINT_PATCH: D3D_PRIMITIVE =
    D3D_PRIMITIVE::CONTROL_POINT_PATCH_21;
pub const D3D11_PRIMITIVE_22_CONTROL_POINT_PATCH: D3D_PRIMITIVE =
    D3D_PRIMITIVE::CONTROL_POINT_PATCH_22;
pub const D3D11_PRIMITIVE_23_CONTROL_POINT_PATCH: D3D_PRIMITIVE =
    D3D_PRIMITIVE::CONTROL_POINT_PATCH_23;
pub const D3D11_PRIMITIVE_24_CONTROL_POINT_PATCH: D3D_PRIMITIVE =
    D3D_PRIMITIVE::CONTROL_POINT_PATCH_24;
pub const D3D11_PRIMITIVE_25_CONTROL_POINT_PATCH: D3D_PRIMITIVE =
    D3D_PRIMITIVE::CONTROL_POINT_PATCH_25;
pub const D3D11_PRIMITIVE_26_CONTROL_POINT_PATCH: D3D_PRIMITIVE =
    D3D_PRIMITIVE::CONTROL_POINT_PATCH_26;
pub const D3D11_PRIMITIVE_27_CONTROL_POINT_PATCH: D3D_PRIMITIVE =
    D3D_PRIMITIVE::CONTROL_POINT_PATCH_27;
pub const D3D11_PRIMITIVE_28_CONTROL_POINT_PATCH: D3D_PRIMITIVE =
    D3D_PRIMITIVE::CONTROL_POINT_PATCH_28;
pub const D3D11_PRIMITIVE_29_CONTROL_POINT_PATCH: D3D_PRIMITIVE =
    D3D_PRIMITIVE::CONTROL_POINT_PATCH_29;
pub const D3D11_PRIMITIVE_30_CONTROL_POINT_PATCH: D3D_PRIMITIVE =
    D3D_PRIMITIVE::CONTROL_POINT_PATCH_30;
pub const D3D11_PRIMITIVE_31_CONTROL_POINT_PATCH: D3D_PRIMITIVE =
    D3D_PRIMITIVE::CONTROL_POINT_PATCH_31;
pub const D3D11_PRIMITIVE_32_CONTROL_POINT_PATCH: D3D_PRIMITIVE =
    D3D_PRIMITIVE::CONTROL_POINT_PATCH_32;

#[repr(C)]
pub enum D3D_PRIMITIVE_TOPOLOGY {
    UNDEFINED = 0,
    POINTLIST = 1,
    LINELIST = 2,
    LINESTRIP = 3,
    TRIANGLELIST = 4,
    TRIANGLESTRIP = 5,
    LINELIST_ADJ = 10,
    LINESTRIP_ADJ = 11,
    TRIANGLELIST_ADJ = 12,
    TRIANGLESTRIP_ADJ = 13,
    CONTROL_POINT_PATCHLIST_1 = 33,
    CONTROL_POINT_PATCHLIST_2 = 34,
    CONTROL_POINT_PATCHLIST_3 = 35,
    CONTROL_POINT_PATCHLIST_4 = 36,
    CONTROL_POINT_PATCHLIST_5 = 37,
    CONTROL_POINT_PATCHLIST_6 = 38,
    CONTROL_POINT_PATCHLIST_7 = 39,
    CONTROL_POINT_PATCHLIST_8 = 40,
    CONTROL_POINT_PATCHLIST_9 = 41,
    CONTROL_POINT_PATCHLIST_10 = 42,
    CONTROL_POINT_PATCHLIST_11 = 43,
    CONTROL_POINT_PATCHLIST_12 = 44,
    CONTROL_POINT_PATCHLIST_13 = 45,
    CONTROL_POINT_PATCHLIST_14 = 46,
    CONTROL_POINT_PATCHLIST_15 = 47,
    CONTROL_POINT_PATCHLIST_16 = 48,
    CONTROL_POINT_PATCHLIST_17 = 49,
    CONTROL_POINT_PATCHLIST_18 = 50,
    CONTROL_POINT_PATCHLIST_19 = 51,
    CONTROL_POINT_PATCHLIST_20 = 52,
    CONTROL_POINT_PATCHLIST_21 = 53,
    CONTROL_POINT_PATCHLIST_22 = 54,
    CONTROL_POINT_PATCHLIST_23 = 55,
    CONTROL_POINT_PATCHLIST_24 = 56,
    CONTROL_POINT_PATCHLIST_25 = 57,
    CONTROL_POINT_PATCHLIST_26 = 58,
    CONTROL_POINT_PATCHLIST_27 = 59,
    CONTROL_POINT_PATCHLIST_28 = 60,
    CONTROL_POINT_PATCHLIST_29 = 61,
    CONTROL_POINT_PATCHLIST_30 = 62,
    CONTROL_POINT_PATCHLIST_31 = 63,
    CONTROL_POINT_PATCHLIST_32 = 64,
}
pub const D3D10_PRIMITIVE_TOPOLOGY_UNDEFINED: D3D_PRIMITIVE_TOPOLOGY =
    D3D_PRIMITIVE_TOPOLOGY::UNDEFINED;
pub const D3D10_PRIMITIVE_TOPOLOGY_POINTLIST: D3D_PRIMITIVE_TOPOLOGY =
    D3D_PRIMITIVE_TOPOLOGY::POINTLIST;
pub const D3D10_PRIMITIVE_TOPOLOGY_LINELIST: D3D_PRIMITIVE_TOPOLOGY =
    D3D_PRIMITIVE_TOPOLOGY::LINELIST;
pub const D3D10_PRIMITIVE_TOPOLOGY_LINESTRIP: D3D_PRIMITIVE_TOPOLOGY =
    D3D_PRIMITIVE_TOPOLOGY::LINESTRIP;
pub const D3D10_PRIMITIVE_TOPOLOGY_TRIANGLELIST: D3D_PRIMITIVE_TOPOLOGY =
    D3D_PRIMITIVE_TOPOLOGY::TRIANGLELIST;
pub const D3D10_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP: D3D_PRIMITIVE_TOPOLOGY =
    D3D_PRIMITIVE_TOPOLOGY::TRIANGLESTRIP;
pub const D3D10_PRIMITIVE_TOPOLOGY_LINELIST_ADJ: D3D_PRIMITIVE_TOPOLOGY =
    D3D_PRIMITIVE_TOPOLOGY::LINELIST_ADJ;
pub const D3D10_PRIMITIVE_TOPOLOGY_LINESTRIP_ADJ: D3D_PRIMITIVE_TOPOLOGY =
    D3D_PRIMITIVE_TOPOLOGY::LINESTRIP_ADJ;
pub const D3D10_PRIMITIVE_TOPOLOGY_TRIANGLELIST_ADJ: D3D_PRIMITIVE_TOPOLOGY =
    D3D_PRIMITIVE_TOPOLOGY::TRIANGLELIST_ADJ;
pub const D3D10_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP_ADJ: D3D_PRIMITIVE_TOPOLOGY =
    D3D_PRIMITIVE_TOPOLOGY::TRIANGLESTRIP_ADJ;
pub const D3D11_PRIMITIVE_TOPOLOGY_UNDEFINED: D3D_PRIMITIVE_TOPOLOGY =
    D3D_PRIMITIVE_TOPOLOGY::UNDEFINED;
pub const D3D11_PRIMITIVE_TOPOLOGY_POINTLIST: D3D_PRIMITIVE_TOPOLOGY =
    D3D_PRIMITIVE_TOPOLOGY::POINTLIST;
pub const D3D11_PRIMITIVE_TOPOLOGY_LINELIST: D3D_PRIMITIVE_TOPOLOGY =
    D3D_PRIMITIVE_TOPOLOGY::LINELIST;
pub const D3D11_PRIMITIVE_TOPOLOGY_LINESTRIP: D3D_PRIMITIVE_TOPOLOGY =
    D3D_PRIMITIVE_TOPOLOGY::LINESTRIP;
pub const D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST: D3D_PRIMITIVE_TOPOLOGY =
    D3D_PRIMITIVE_TOPOLOGY::TRIANGLELIST;
pub const D3D11_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP: D3D_PRIMITIVE_TOPOLOGY =
    D3D_PRIMITIVE_TOPOLOGY::TRIANGLESTRIP;
pub const D3D11_PRIMITIVE_TOPOLOGY_LINELIST_ADJ: D3D_PRIMITIVE_TOPOLOGY =
    D3D_PRIMITIVE_TOPOLOGY::LINELIST_ADJ;
pub const D3D11_PRIMITIVE_TOPOLOGY_LINESTRIP_ADJ: D3D_PRIMITIVE_TOPOLOGY =
    D3D_PRIMITIVE_TOPOLOGY::LINESTRIP_ADJ;
pub const D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST_ADJ: D3D_PRIMITIVE_TOPOLOGY =
    D3D_PRIMITIVE_TOPOLOGY::TRIANGLELIST_ADJ;
pub const D3D11_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP_ADJ: D3D_PRIMITIVE_TOPOLOGY =
    D3D_PRIMITIVE_TOPOLOGY::TRIANGLESTRIP_ADJ;
pub const D3D11_PRIMITIVE_TOPOLOGY_1_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY =
    D3D_PRIMITIVE_TOPOLOGY::CONTROL_POINT_PATCHLIST_1;
pub const D3D11_PRIMITIVE_TOPOLOGY_2_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY =
    D3D_PRIMITIVE_TOPOLOGY::CONTROL_POINT_PATCHLIST_2;
pub const D3D11_PRIMITIVE_TOPOLOGY_3_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY =
    D3D_PRIMITIVE_TOPOLOGY::CONTROL_POINT_PATCHLIST_3;
pub const D3D11_PRIMITIVE_TOPOLOGY_4_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY =
    D3D_PRIMITIVE_TOPOLOGY::CONTROL_POINT_PATCHLIST_4;
pub const D3D11_PRIMITIVE_TOPOLOGY_5_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY =
    D3D_PRIMITIVE_TOPOLOGY::CONTROL_POINT_PATCHLIST_5;
pub const D3D11_PRIMITIVE_TOPOLOGY_6_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY =
    D3D_PRIMITIVE_TOPOLOGY::CONTROL_POINT_PATCHLIST_6;
pub const D3D11_PRIMITIVE_TOPOLOGY_7_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY =
    D3D_PRIMITIVE_TOPOLOGY::CONTROL_POINT_PATCHLIST_7;
pub const D3D11_PRIMITIVE_TOPOLOGY_8_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY =
    D3D_PRIMITIVE_TOPOLOGY::CONTROL_POINT_PATCHLIST_8;
pub const D3D11_PRIMITIVE_TOPOLOGY_9_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY =
    D3D_PRIMITIVE_TOPOLOGY::CONTROL_POINT_PATCHLIST_9;
pub const D3D11_PRIMITIVE_TOPOLOGY_10_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY =
    D3D_PRIMITIVE_TOPOLOGY::CONTROL_POINT_PATCHLIST_10;
pub const D3D11_PRIMITIVE_TOPOLOGY_11_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY =
    D3D_PRIMITIVE_TOPOLOGY::CONTROL_POINT_PATCHLIST_11;
pub const D3D11_PRIMITIVE_TOPOLOGY_12_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY =
    D3D_PRIMITIVE_TOPOLOGY::CONTROL_POINT_PATCHLIST_12;
pub const D3D11_PRIMITIVE_TOPOLOGY_13_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY =
    D3D_PRIMITIVE_TOPOLOGY::CONTROL_POINT_PATCHLIST_13;
pub const D3D11_PRIMITIVE_TOPOLOGY_14_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY =
    D3D_PRIMITIVE_TOPOLOGY::CONTROL_POINT_PATCHLIST_14;
pub const D3D11_PRIMITIVE_TOPOLOGY_15_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY =
    D3D_PRIMITIVE_TOPOLOGY::CONTROL_POINT_PATCHLIST_15;
pub const D3D11_PRIMITIVE_TOPOLOGY_16_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY =
    D3D_PRIMITIVE_TOPOLOGY::CONTROL_POINT_PATCHLIST_16;
pub const D3D11_PRIMITIVE_TOPOLOGY_17_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY =
    D3D_PRIMITIVE_TOPOLOGY::CONTROL_POINT_PATCHLIST_17;
pub const D3D11_PRIMITIVE_TOPOLOGY_18_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY =
    D3D_PRIMITIVE_TOPOLOGY::CONTROL_POINT_PATCHLIST_18;
pub const D3D11_PRIMITIVE_TOPOLOGY_19_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY =
    D3D_PRIMITIVE_TOPOLOGY::CONTROL_POINT_PATCHLIST_19;
pub const D3D11_PRIMITIVE_TOPOLOGY_20_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY =
    D3D_PRIMITIVE_TOPOLOGY::CONTROL_POINT_PATCHLIST_20;
pub const D3D11_PRIMITIVE_TOPOLOGY_21_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY =
    D3D_PRIMITIVE_TOPOLOGY::CONTROL_POINT_PATCHLIST_21;
pub const D3D11_PRIMITIVE_TOPOLOGY_22_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY =
    D3D_PRIMITIVE_TOPOLOGY::CONTROL_POINT_PATCHLIST_22;
pub const D3D11_PRIMITIVE_TOPOLOGY_23_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY =
    D3D_PRIMITIVE_TOPOLOGY::CONTROL_POINT_PATCHLIST_23;
pub const D3D11_PRIMITIVE_TOPOLOGY_24_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY =
    D3D_PRIMITIVE_TOPOLOGY::CONTROL_POINT_PATCHLIST_24;
pub const D3D11_PRIMITIVE_TOPOLOGY_25_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY =
    D3D_PRIMITIVE_TOPOLOGY::CONTROL_POINT_PATCHLIST_25;
pub const D3D11_PRIMITIVE_TOPOLOGY_26_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY =
    D3D_PRIMITIVE_TOPOLOGY::CONTROL_POINT_PATCHLIST_26;
pub const D3D11_PRIMITIVE_TOPOLOGY_27_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY =
    D3D_PRIMITIVE_TOPOLOGY::CONTROL_POINT_PATCHLIST_27;
pub const D3D11_PRIMITIVE_TOPOLOGY_28_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY =
    D3D_PRIMITIVE_TOPOLOGY::CONTROL_POINT_PATCHLIST_28;
pub const D3D11_PRIMITIVE_TOPOLOGY_29_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY =
    D3D_PRIMITIVE_TOPOLOGY::CONTROL_POINT_PATCHLIST_29;
pub const D3D11_PRIMITIVE_TOPOLOGY_30_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY =
    D3D_PRIMITIVE_TOPOLOGY::CONTROL_POINT_PATCHLIST_30;
pub const D3D11_PRIMITIVE_TOPOLOGY_31_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY =
    D3D_PRIMITIVE_TOPOLOGY::CONTROL_POINT_PATCHLIST_31;
pub const D3D11_PRIMITIVE_TOPOLOGY_32_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY =
    D3D_PRIMITIVE_TOPOLOGY::CONTROL_POINT_PATCHLIST_32;

#[repr(C)]
pub enum D3D_REGISTER_COMPONENT_TYPE {
    UNKNOWN = 0,
    UINT32 = 1,
    SINT32 = 2,
    FLOAT32 = 3,
}
pub const D3D10_REGISTER_COMPONENT_UNKNOWN: D3D_REGISTER_COMPONENT_TYPE =
    D3D_REGISTER_COMPONENT_TYPE::UNKNOWN;
pub const D3D10_REGISTER_COMPONENT_UINT32: D3D_REGISTER_COMPONENT_TYPE =
    D3D_REGISTER_COMPONENT_TYPE::UINT32;
pub const D3D10_REGISTER_COMPONENT_SINT32: D3D_REGISTER_COMPONENT_TYPE =
    D3D_REGISTER_COMPONENT_TYPE::SINT32;
pub const D3D10_REGISTER_COMPONENT_FLOAT32: D3D_REGISTER_COMPONENT_TYPE =
    D3D_REGISTER_COMPONENT_TYPE::FLOAT32;

#[repr(C)]
pub enum D3D_RESOURCE_RETURN_TYPE {
    UNORM = 1,
    SNORM = 2,
    SINT = 3,
    UINT = 4,
    FLOAT = 5,
    MIXED = 6,
    DOUBLE = 7,
    CONTINUED = 8,
}
pub const D3D10_RETURN_TYPE_UNORM: D3D_RESOURCE_RETURN_TYPE = D3D_RESOURCE_RETURN_TYPE::UNORM;
pub const D3D10_RETURN_TYPE_SNORM: D3D_RESOURCE_RETURN_TYPE = D3D_RESOURCE_RETURN_TYPE::SNORM;
pub const D3D10_RETURN_TYPE_SINT: D3D_RESOURCE_RETURN_TYPE = D3D_RESOURCE_RETURN_TYPE::SINT;
pub const D3D10_RETURN_TYPE_UINT: D3D_RESOURCE_RETURN_TYPE = D3D_RESOURCE_RETURN_TYPE::UINT;
pub const D3D10_RETURN_TYPE_FLOAT: D3D_RESOURCE_RETURN_TYPE = D3D_RESOURCE_RETURN_TYPE::FLOAT;
pub const D3D10_RETURN_TYPE_MIXED: D3D_RESOURCE_RETURN_TYPE = D3D_RESOURCE_RETURN_TYPE::MIXED;
pub const D3D11_RETURN_TYPE_UNORM: D3D_RESOURCE_RETURN_TYPE = D3D_RESOURCE_RETURN_TYPE::UNORM;
pub const D3D11_RETURN_TYPE_SNORM: D3D_RESOURCE_RETURN_TYPE = D3D_RESOURCE_RETURN_TYPE::SNORM;
pub const D3D11_RETURN_TYPE_SINT: D3D_RESOURCE_RETURN_TYPE = D3D_RESOURCE_RETURN_TYPE::SINT;
pub const D3D11_RETURN_TYPE_UINT: D3D_RESOURCE_RETURN_TYPE = D3D_RESOURCE_RETURN_TYPE::UINT;
pub const D3D11_RETURN_TYPE_FLOAT: D3D_RESOURCE_RETURN_TYPE = D3D_RESOURCE_RETURN_TYPE::FLOAT;
pub const D3D11_RETURN_TYPE_MIXED: D3D_RESOURCE_RETURN_TYPE = D3D_RESOURCE_RETURN_TYPE::MIXED;
pub const D3D11_RETURN_TYPE_DOUBLE: D3D_RESOURCE_RETURN_TYPE = D3D_RESOURCE_RETURN_TYPE::DOUBLE;
pub const D3D11_RETURN_TYPE_CONTINUED: D3D_RESOURCE_RETURN_TYPE =
    D3D_RESOURCE_RETURN_TYPE::CONTINUED;

#[repr(C)]
pub enum D3D_SHADER_CBUFFER_FLAGS {
    USERPACKED = 1,
    FORCE_DWORD = 0x7fffffff,
}
pub const D3D10_CBF_USERPACKED: D3D_SHADER_CBUFFER_FLAGS = D3D_SHADER_CBUFFER_FLAGS::USERPACKED;

#[repr(C)]
pub enum D3D_SHADER_INPUT_FLAGS {
    USERPACKED = 0x1,
    COMPARISON_SAMPLER = 0x2,
    TEXTURE_COMPONENT_0 = 0x4,
    TEXTURE_COMPONENT_1 = 0x8,
    TEXTURE_COMPONENTS = 0xc,
    UNUSED = 0x10,
    FORCE_DWORD = 0x7fffffff,
}
pub const D3D10_SIF_USERPACKED: D3D_SHADER_INPUT_FLAGS = D3D_SHADER_INPUT_FLAGS::USERPACKED;
pub const D3D10_SIF_COMPARISON_SAMPLER: D3D_SHADER_INPUT_FLAGS =
    D3D_SHADER_INPUT_FLAGS::COMPARISON_SAMPLER;
pub const D3D10_SIF_TEXTURE_COMPONENT_0: D3D_SHADER_INPUT_FLAGS =
    D3D_SHADER_INPUT_FLAGS::TEXTURE_COMPONENT_0;
pub const D3D10_SIF_TEXTURE_COMPONENT_1: D3D_SHADER_INPUT_FLAGS =
    D3D_SHADER_INPUT_FLAGS::TEXTURE_COMPONENT_1;
pub const D3D10_SIF_TEXTURE_COMPONENTS: D3D_SHADER_INPUT_FLAGS =
    D3D_SHADER_INPUT_FLAGS::TEXTURE_COMPONENTS;

#[repr(C)]
pub enum D3D_SHADER_INPUT_TYPE {
    CBUFFER = 0,
    TBUFFER = 1,
    TEXTURE = 2,
    SAMPLER = 3,
    UAV_RWTYPED = 4,
    STRUCTURED = 5,
    UAV_RWSTRUCTURED = 6,
    BYTEADDRESS = 7,
    UAV_RWBYTEADDRESS = 8,
    UAV_APPEND_STRUCTURED = 9,
    UAV_CONSUME_STRUCTURED = 10,
    UAV_RWSTRUCTURED_WITH_COUNTER = 11,
}
pub const D3D10_SIT_CBUFFER: D3D_SHADER_INPUT_TYPE = D3D_SHADER_INPUT_TYPE::CBUFFER;
pub const D3D10_SIT_TBUFFER: D3D_SHADER_INPUT_TYPE = D3D_SHADER_INPUT_TYPE::TBUFFER;
pub const D3D10_SIT_TEXTURE: D3D_SHADER_INPUT_TYPE = D3D_SHADER_INPUT_TYPE::TEXTURE;
pub const D3D10_SIT_SAMPLER: D3D_SHADER_INPUT_TYPE = D3D_SHADER_INPUT_TYPE::SAMPLER;
pub const D3D11_SIT_UAV_RWTYPED: D3D_SHADER_INPUT_TYPE = D3D_SHADER_INPUT_TYPE::UAV_RWTYPED;
pub const D3D11_SIT_STRUCTURED: D3D_SHADER_INPUT_TYPE = D3D_SHADER_INPUT_TYPE::STRUCTURED;
pub const D3D11_SIT_UAV_RWSTRUCTURED: D3D_SHADER_INPUT_TYPE =
    D3D_SHADER_INPUT_TYPE::UAV_RWSTRUCTURED;
pub const D3D11_SIT_BYTEADDRESS: D3D_SHADER_INPUT_TYPE = D3D_SHADER_INPUT_TYPE::BYTEADDRESS;
pub const D3D11_SIT_UAV_RWBYTEADDRESS: D3D_SHADER_INPUT_TYPE =
    D3D_SHADER_INPUT_TYPE::UAV_RWBYTEADDRESS;
pub const D3D11_SIT_UAV_APPEND_STRUCTURED: D3D_SHADER_INPUT_TYPE =
    D3D_SHADER_INPUT_TYPE::UAV_APPEND_STRUCTURED;
pub const D3D11_SIT_UAV_CONSUME_STRUCTURED: D3D_SHADER_INPUT_TYPE =
    D3D_SHADER_INPUT_TYPE::UAV_CONSUME_STRUCTURED;
pub const D3D11_SIT_UAV_RWSTRUCTURED_WITH_COUNTER: D3D_SHADER_INPUT_TYPE =
    D3D_SHADER_INPUT_TYPE::UAV_RWSTRUCTURED_WITH_COUNTER;

#[repr(C)]
pub enum D3D_SHADER_VARIABLE_CLASS {
    SCALAR = 0,
    VECTOR,
    MATRIX_ROWS,
    MATRIX_COLUMNS,
    OBJECT,
    STRUCT,
    INTERFACE_CLASS,
    INTERFACE_POINTER,
    FORCE_DWORD = 0x7fffffff,
}
pub const D3D10_SVC_SCALAR: D3D_SHADER_VARIABLE_CLASS = D3D_SHADER_VARIABLE_CLASS::SCALAR;
pub const D3D10_SVC_VECTOR: D3D_SHADER_VARIABLE_CLASS = D3D_SHADER_VARIABLE_CLASS::VECTOR;
pub const D3D10_SVC_MATRIX_ROWS: D3D_SHADER_VARIABLE_CLASS = D3D_SHADER_VARIABLE_CLASS::MATRIX_ROWS;
pub const D3D10_SVC_MATRIX_COLUMNS: D3D_SHADER_VARIABLE_CLASS =
    D3D_SHADER_VARIABLE_CLASS::MATRIX_COLUMNS;
pub const D3D10_SVC_OBJECT: D3D_SHADER_VARIABLE_CLASS = D3D_SHADER_VARIABLE_CLASS::OBJECT;
pub const D3D10_SVC_STRUCT: D3D_SHADER_VARIABLE_CLASS = D3D_SHADER_VARIABLE_CLASS::STRUCT;
pub const D3D11_SVC_INTERFACE_CLASS: D3D_SHADER_VARIABLE_CLASS =
    D3D_SHADER_VARIABLE_CLASS::INTERFACE_CLASS;
pub const D3D11_SVC_INTERFACE_POINTER: D3D_SHADER_VARIABLE_CLASS =
    D3D_SHADER_VARIABLE_CLASS::INTERFACE_POINTER;

#[repr(C)]
pub enum D3D_SHADER_VARIABLE_FLAGS {
    USERPACKED = 1,
    USED = 2,
    INTERFACE_POINTER = 4,
    INTERFACE_PARAMETER = 8,
    FORCE_DWORD = 0x7fffffff,
}
pub const D3D10_SVF_USERPACKED: D3D_SHADER_VARIABLE_FLAGS = D3D_SHADER_VARIABLE_FLAGS::USERPACKED;
pub const D3D10_SVF_USED: D3D_SHADER_VARIABLE_FLAGS = D3D_SHADER_VARIABLE_FLAGS::USED;
pub const D3D11_SVF_INTERFACE_POINTER: D3D_SHADER_VARIABLE_FLAGS =
    D3D_SHADER_VARIABLE_FLAGS::INTERFACE_POINTER;
pub const D3D11_SVF_INTERFACE_PARAMETER: D3D_SHADER_VARIABLE_FLAGS =
    D3D_SHADER_VARIABLE_FLAGS::INTERFACE_PARAMETER;

#[repr(C)]
pub enum D3D_SHADER_VARIABLE_TYPE {
    VOID = 0,
    BOOL = 1,
    INT = 2,
    FLOAT = 3,
    STRING = 4,
    TEXTURE = 5,
    TEXTURE1D = 6,
    TEXTURE2D = 7,
    TEXTURE3D = 8,
    TEXTURECUBE = 9,
    SAMPLER = 10,
    SAMPLER1D = 11,
    SAMPLER2D = 12,
    SAMPLER3D = 13,
    SAMPLERCUBE = 14,
    PIXELSHADER = 15,
    VERTEXSHADER = 16,
    PIXELFRAGMENT = 17,
    VERTEXFRAGMENT = 18,
    UINT = 19,
    UINT8 = 20,
    GEOMETRYSHADER = 21,
    RASTERIZER = 22,
    DEPTHSTENCIL = 23,
    BLEND = 24,
    BUFFER = 25,
    CBUFFER = 26,
    TBUFFER = 27,
    TEXTURE1DARRAY = 28,
    TEXTURE2DARRAY = 29,
    RENDERTARGETVIEW = 30,
    DEPTHSTENCILVIEW = 31,
    TEXTURE2DMS = 32,
    TEXTURE2DMSARRAY = 33,
    TEXTURECUBEARRAY = 34,
    HULLSHADER = 35,
    DOMAINSHADER = 36,
    INTERFACE_POINTER = 37,
    COMPUTESHADER = 38,
    DOUBLE = 39,
    RWTEXTURE1D = 40,
    RWTEXTURE1DARRAY = 41,
    RWTEXTURE2D = 42,
    RWTEXTURE2DARRAY = 43,
    RWTEXTURE3D = 44,
    RWBUFFER = 45,
    BYTEADDRESS_BUFFER = 46,
    RWBYTEADDRESS_BUFFER = 47,
    STRUCTURED_BUFFER = 48,
    RWSTRUCTURED_BUFFER = 49,
    APPEND_STRUCTURED_BUFFER = 50,
    CONSUME_STRUCTURED_BUFFER = 51,
    MIN8FLOAT = 52,
    MIN10FLOAT = 53,
    MIN16FLOAT = 54,
    MIN12INT = 55,
    MIN16INT = 56,
    MIN16UINT = 57,
    FORCE_DWORD = 0x7fffffff,
}
pub const D3D10_SVT_VOID: D3D_SHADER_VARIABLE_TYPE = D3D_SHADER_VARIABLE_TYPE::VOID;
pub const D3D10_SVT_BOOL: D3D_SHADER_VARIABLE_TYPE = D3D_SHADER_VARIABLE_TYPE::BOOL;
pub const D3D10_SVT_INT: D3D_SHADER_VARIABLE_TYPE = D3D_SHADER_VARIABLE_TYPE::INT;
pub const D3D10_SVT_FLOAT: D3D_SHADER_VARIABLE_TYPE = D3D_SHADER_VARIABLE_TYPE::FLOAT;
pub const D3D10_SVT_STRING: D3D_SHADER_VARIABLE_TYPE = D3D_SHADER_VARIABLE_TYPE::STRING;
pub const D3D10_SVT_TEXTURE: D3D_SHADER_VARIABLE_TYPE = D3D_SHADER_VARIABLE_TYPE::TEXTURE;
pub const D3D10_SVT_TEXTURE1D: D3D_SHADER_VARIABLE_TYPE = D3D_SHADER_VARIABLE_TYPE::TEXTURE1D;
pub const D3D10_SVT_TEXTURE2D: D3D_SHADER_VARIABLE_TYPE = D3D_SHADER_VARIABLE_TYPE::TEXTURE2D;
pub const D3D10_SVT_TEXTURE3D: D3D_SHADER_VARIABLE_TYPE = D3D_SHADER_VARIABLE_TYPE::TEXTURE3D;
pub const D3D10_SVT_TEXTURECUBE: D3D_SHADER_VARIABLE_TYPE = D3D_SHADER_VARIABLE_TYPE::TEXTURECUBE;
pub const D3D10_SVT_SAMPLER: D3D_SHADER_VARIABLE_TYPE = D3D_SHADER_VARIABLE_TYPE::SAMPLER;
pub const D3D10_SVT_SAMPLER1D: D3D_SHADER_VARIABLE_TYPE = D3D_SHADER_VARIABLE_TYPE::SAMPLER1D;
pub const D3D10_SVT_SAMPLER2D: D3D_SHADER_VARIABLE_TYPE = D3D_SHADER_VARIABLE_TYPE::SAMPLER2D;
pub const D3D10_SVT_SAMPLER3D: D3D_SHADER_VARIABLE_TYPE = D3D_SHADER_VARIABLE_TYPE::SAMPLER3D;
pub const D3D10_SVT_SAMPLERCUBE: D3D_SHADER_VARIABLE_TYPE = D3D_SHADER_VARIABLE_TYPE::SAMPLERCUBE;
pub const D3D10_SVT_PIXELSHADER: D3D_SHADER_VARIABLE_TYPE = D3D_SHADER_VARIABLE_TYPE::PIXELSHADER;
pub const D3D10_SVT_VERTEXSHADER: D3D_SHADER_VARIABLE_TYPE = D3D_SHADER_VARIABLE_TYPE::VERTEXSHADER;
pub const D3D10_SVT_PIXELFRAGMENT: D3D_SHADER_VARIABLE_TYPE =
    D3D_SHADER_VARIABLE_TYPE::PIXELFRAGMENT;
pub const D3D10_SVT_VERTEXFRAGMENT: D3D_SHADER_VARIABLE_TYPE =
    D3D_SHADER_VARIABLE_TYPE::VERTEXFRAGMENT;
pub const D3D10_SVT_UINT: D3D_SHADER_VARIABLE_TYPE = D3D_SHADER_VARIABLE_TYPE::UINT;
pub const D3D10_SVT_UINT8: D3D_SHADER_VARIABLE_TYPE = D3D_SHADER_VARIABLE_TYPE::UINT8;
pub const D3D10_SVT_GEOMETRYSHADER: D3D_SHADER_VARIABLE_TYPE =
    D3D_SHADER_VARIABLE_TYPE::GEOMETRYSHADER;
pub const D3D10_SVT_RASTERIZER: D3D_SHADER_VARIABLE_TYPE = D3D_SHADER_VARIABLE_TYPE::RASTERIZER;
pub const D3D10_SVT_DEPTHSTENCIL: D3D_SHADER_VARIABLE_TYPE = D3D_SHADER_VARIABLE_TYPE::DEPTHSTENCIL;
pub const D3D10_SVT_BLEND: D3D_SHADER_VARIABLE_TYPE = D3D_SHADER_VARIABLE_TYPE::BLEND;
pub const D3D10_SVT_BUFFER: D3D_SHADER_VARIABLE_TYPE = D3D_SHADER_VARIABLE_TYPE::BUFFER;
pub const D3D10_SVT_CBUFFER: D3D_SHADER_VARIABLE_TYPE = D3D_SHADER_VARIABLE_TYPE::CBUFFER;
pub const D3D10_SVT_TBUFFER: D3D_SHADER_VARIABLE_TYPE = D3D_SHADER_VARIABLE_TYPE::TBUFFER;
pub const D3D10_SVT_TEXTURE1DARRAY: D3D_SHADER_VARIABLE_TYPE =
    D3D_SHADER_VARIABLE_TYPE::TEXTURE1DARRAY;
pub const D3D10_SVT_TEXTURE2DARRAY: D3D_SHADER_VARIABLE_TYPE =
    D3D_SHADER_VARIABLE_TYPE::TEXTURE2DARRAY;
pub const D3D10_SVT_RENDERTARGETVIEW: D3D_SHADER_VARIABLE_TYPE =
    D3D_SHADER_VARIABLE_TYPE::RENDERTARGETVIEW;
pub const D3D10_SVT_DEPTHSTENCILVIEW: D3D_SHADER_VARIABLE_TYPE =
    D3D_SHADER_VARIABLE_TYPE::DEPTHSTENCILVIEW;
pub const D3D10_SVT_TEXTURE2DMS: D3D_SHADER_VARIABLE_TYPE = D3D_SHADER_VARIABLE_TYPE::TEXTURE2DMS;
pub const D3D10_SVT_TEXTURE2DMSARRAY: D3D_SHADER_VARIABLE_TYPE =
    D3D_SHADER_VARIABLE_TYPE::TEXTURE2DMSARRAY;
pub const D3D10_SVT_TEXTURECUBEARRAY: D3D_SHADER_VARIABLE_TYPE =
    D3D_SHADER_VARIABLE_TYPE::TEXTURECUBEARRAY;
pub const D3D11_SVT_HULLSHADER: D3D_SHADER_VARIABLE_TYPE = D3D_SHADER_VARIABLE_TYPE::HULLSHADER;
pub const D3D11_SVT_DOMAINSHADER: D3D_SHADER_VARIABLE_TYPE = D3D_SHADER_VARIABLE_TYPE::DOMAINSHADER;
pub const D3D11_SVT_INTERFACE_POINTER: D3D_SHADER_VARIABLE_TYPE =
    D3D_SHADER_VARIABLE_TYPE::INTERFACE_POINTER;
pub const D3D11_SVT_COMPUTESHADER: D3D_SHADER_VARIABLE_TYPE =
    D3D_SHADER_VARIABLE_TYPE::COMPUTESHADER;
pub const D3D11_SVT_DOUBLE: D3D_SHADER_VARIABLE_TYPE = D3D_SHADER_VARIABLE_TYPE::DOUBLE;
pub const D3D11_SVT_RWTEXTURE1D: D3D_SHADER_VARIABLE_TYPE = D3D_SHADER_VARIABLE_TYPE::RWTEXTURE1D;
pub const D3D11_SVT_RWTEXTURE1DARRAY: D3D_SHADER_VARIABLE_TYPE =
    D3D_SHADER_VARIABLE_TYPE::RWTEXTURE1DARRAY;
pub const D3D11_SVT_RWTEXTURE2D: D3D_SHADER_VARIABLE_TYPE = D3D_SHADER_VARIABLE_TYPE::RWTEXTURE2D;
pub const D3D11_SVT_RWTEXTURE2DARRAY: D3D_SHADER_VARIABLE_TYPE =
    D3D_SHADER_VARIABLE_TYPE::RWTEXTURE2DARRAY;
pub const D3D11_SVT_RWTEXTURE3D: D3D_SHADER_VARIABLE_TYPE = D3D_SHADER_VARIABLE_TYPE::RWTEXTURE3D;
pub const D3D11_SVT_RWBUFFER: D3D_SHADER_VARIABLE_TYPE = D3D_SHADER_VARIABLE_TYPE::RWBUFFER;
pub const D3D11_SVT_BYTEADDRESS_BUFFER: D3D_SHADER_VARIABLE_TYPE =
    D3D_SHADER_VARIABLE_TYPE::BYTEADDRESS_BUFFER;
pub const D3D11_SVT_RWBYTEADDRESS_BUFFER: D3D_SHADER_VARIABLE_TYPE =
    D3D_SHADER_VARIABLE_TYPE::RWBYTEADDRESS_BUFFER;
pub const D3D11_SVT_STRUCTURED_BUFFER: D3D_SHADER_VARIABLE_TYPE =
    D3D_SHADER_VARIABLE_TYPE::STRUCTURED_BUFFER;
pub const D3D11_SVT_RWSTRUCTURED_BUFFER: D3D_SHADER_VARIABLE_TYPE =
    D3D_SHADER_VARIABLE_TYPE::RWSTRUCTURED_BUFFER;
pub const D3D11_SVT_APPEND_STRUCTURED_BUFFER: D3D_SHADER_VARIABLE_TYPE =
    D3D_SHADER_VARIABLE_TYPE::APPEND_STRUCTURED_BUFFER;
pub const D3D11_SVT_CONSUME_STRUCTURED_BUFFER: D3D_SHADER_VARIABLE_TYPE =
    D3D_SHADER_VARIABLE_TYPE::CONSUME_STRUCTURED_BUFFER;

#[repr(C)]
pub enum D3D_SRV_DIMENSION {
    UNKNOWN = 0,
    BUFFER = 1,
    TEXTURE1D = 2,
    TEXTURE1DARRAY = 3,
    TEXTURE2D = 4,
    TEXTURE2DARRAY = 5,
    TEXTURE2DMS = 6,
    TEXTURE2DMSARRAY = 7,
    TEXTURE3D = 8,
    TEXTURECUBE = 9,
    TEXTURECUBEARRAY = 10,
    BUFFEREX = 11,
}
pub const D3D10_SRV_DIMENSION_UNKNOWN: D3D_SRV_DIMENSION = D3D_SRV_DIMENSION::UNKNOWN;
pub const D3D10_SRV_DIMENSION_BUFFER: D3D_SRV_DIMENSION = D3D_SRV_DIMENSION::BUFFER;
pub const D3D10_SRV_DIMENSION_TEXTURE1D: D3D_SRV_DIMENSION = D3D_SRV_DIMENSION::TEXTURE1D;
pub const D3D10_SRV_DIMENSION_TEXTURE1DARRAY: D3D_SRV_DIMENSION = D3D_SRV_DIMENSION::TEXTURE1DARRAY;
pub const D3D10_SRV_DIMENSION_TEXTURE2D: D3D_SRV_DIMENSION = D3D_SRV_DIMENSION::TEXTURE2D;
pub const D3D10_SRV_DIMENSION_TEXTURE2DARRAY: D3D_SRV_DIMENSION = D3D_SRV_DIMENSION::TEXTURE2DARRAY;
pub const D3D10_SRV_DIMENSION_TEXTURE2DMS: D3D_SRV_DIMENSION = D3D_SRV_DIMENSION::TEXTURE2DMS;
pub const D3D10_SRV_DIMENSION_TEXTURE2DMSARRAY: D3D_SRV_DIMENSION =
    D3D_SRV_DIMENSION::TEXTURE2DMSARRAY;
pub const D3D10_SRV_DIMENSION_TEXTURE3D: D3D_SRV_DIMENSION = D3D_SRV_DIMENSION::TEXTURE3D;
pub const D3D10_SRV_DIMENSION_TEXTURECUBE: D3D_SRV_DIMENSION = D3D_SRV_DIMENSION::TEXTURECUBE;
pub const D3D10_1_SRV_DIMENSION_UNKNOWN: D3D_SRV_DIMENSION = D3D_SRV_DIMENSION::UNKNOWN;
pub const D3D10_1_SRV_DIMENSION_BUFFER: D3D_SRV_DIMENSION = D3D_SRV_DIMENSION::BUFFER;
pub const D3D10_1_SRV_DIMENSION_TEXTURE1D: D3D_SRV_DIMENSION = D3D_SRV_DIMENSION::TEXTURE1D;
pub const D3D10_1_SRV_DIMENSION_TEXTURE1DARRAY: D3D_SRV_DIMENSION =
    D3D_SRV_DIMENSION::TEXTURE1DARRAY;
pub const D3D10_1_SRV_DIMENSION_TEXTURE2D: D3D_SRV_DIMENSION = D3D_SRV_DIMENSION::TEXTURE2D;
pub const D3D10_1_SRV_DIMENSION_TEXTURE2DARRAY: D3D_SRV_DIMENSION =
    D3D_SRV_DIMENSION::TEXTURE2DARRAY;
pub const D3D10_1_SRV_DIMENSION_TEXTURE2DMS: D3D_SRV_DIMENSION = D3D_SRV_DIMENSION::TEXTURE2DMS;
pub const D3D10_1_SRV_DIMENSION_TEXTURE2DMSARRAY: D3D_SRV_DIMENSION =
    D3D_SRV_DIMENSION::TEXTURE2DMSARRAY;
pub const D3D10_1_SRV_DIMENSION_TEXTURE3D: D3D_SRV_DIMENSION = D3D_SRV_DIMENSION::TEXTURE3D;
pub const D3D10_1_SRV_DIMENSION_TEXTURECUBE: D3D_SRV_DIMENSION = D3D_SRV_DIMENSION::TEXTURECUBE;
pub const D3D10_1_SRV_DIMENSION_TEXTURECUBEARRAY: D3D_SRV_DIMENSION =
    D3D_SRV_DIMENSION::TEXTURECUBEARRAY;
pub const D3D11_SRV_DIMENSION_UNKNOWN: D3D_SRV_DIMENSION = D3D_SRV_DIMENSION::UNKNOWN;
pub const D3D11_SRV_DIMENSION_BUFFER: D3D_SRV_DIMENSION = D3D_SRV_DIMENSION::BUFFER;
pub const D3D11_SRV_DIMENSION_TEXTURE1D: D3D_SRV_DIMENSION = D3D_SRV_DIMENSION::TEXTURE1D;
pub const D3D11_SRV_DIMENSION_TEXTURE1DARRAY: D3D_SRV_DIMENSION = D3D_SRV_DIMENSION::TEXTURE1DARRAY;
pub const D3D11_SRV_DIMENSION_TEXTURE2D: D3D_SRV_DIMENSION = D3D_SRV_DIMENSION::TEXTURE2D;
pub const D3D11_SRV_DIMENSION_TEXTURE2DARRAY: D3D_SRV_DIMENSION = D3D_SRV_DIMENSION::TEXTURE2DARRAY;
pub const D3D11_SRV_DIMENSION_TEXTURE2DMS: D3D_SRV_DIMENSION = D3D_SRV_DIMENSION::TEXTURE2DMS;
pub const D3D11_SRV_DIMENSION_TEXTURE2DMSARRAY: D3D_SRV_DIMENSION =
    D3D_SRV_DIMENSION::TEXTURE2DMSARRAY;
pub const D3D11_SRV_DIMENSION_TEXTURE3D: D3D_SRV_DIMENSION = D3D_SRV_DIMENSION::TEXTURE3D;
pub const D3D11_SRV_DIMENSION_TEXTURECUBE: D3D_SRV_DIMENSION = D3D_SRV_DIMENSION::TEXTURECUBE;
pub const D3D11_SRV_DIMENSION_TEXTURECUBEARRAY: D3D_SRV_DIMENSION =
    D3D_SRV_DIMENSION::TEXTURECUBEARRAY;
pub const D3D11_SRV_DIMENSION_BUFFEREX: D3D_SRV_DIMENSION = D3D_SRV_DIMENSION::BUFFEREX;

#[repr(C)]
pub enum D3D_TESSELLATOR_DOMAIN {
    UNDEFINED = 0,
    ISOLINE = 1,
    TRI = 2,
    QUAD = 3,
}
pub const D3D11_TESSELLATOR_DOMAIN_UNDEFINED: D3D_TESSELLATOR_DOMAIN =
    D3D_TESSELLATOR_DOMAIN::UNDEFINED;
pub const D3D11_TESSELLATOR_DOMAIN_ISOLINE: D3D_TESSELLATOR_DOMAIN =
    D3D_TESSELLATOR_DOMAIN::ISOLINE;
pub const D3D11_TESSELLATOR_DOMAIN_TRI: D3D_TESSELLATOR_DOMAIN = D3D_TESSELLATOR_DOMAIN::TRI;
pub const D3D11_TESSELLATOR_DOMAIN_QUAD: D3D_TESSELLATOR_DOMAIN = D3D_TESSELLATOR_DOMAIN::QUAD;

#[repr(C)]
pub enum D3D_TESSELLATOR_OUTPUT_PRIMITIVE {
    UNDEFINED = 0,
    POINT = 1,
    LINE = 2,
    TRIANGLE_CW = 3,
    TRIANGLE_CCW = 4,
}
pub const D3D11_TESSELLATOR_OUTPUT_UNDEFINED: D3D_TESSELLATOR_OUTPUT_PRIMITIVE =
    D3D_TESSELLATOR_OUTPUT_PRIMITIVE::UNDEFINED;
pub const D3D11_TESSELLATOR_OUTPUT_POINT: D3D_TESSELLATOR_OUTPUT_PRIMITIVE =
    D3D_TESSELLATOR_OUTPUT_PRIMITIVE::POINT;
pub const D3D11_TESSELLATOR_OUTPUT_LINE: D3D_TESSELLATOR_OUTPUT_PRIMITIVE =
    D3D_TESSELLATOR_OUTPUT_PRIMITIVE::LINE;
pub const D3D11_TESSELLATOR_OUTPUT_TRIANGLE_CW: D3D_TESSELLATOR_OUTPUT_PRIMITIVE =
    D3D_TESSELLATOR_OUTPUT_PRIMITIVE::TRIANGLE_CW;
pub const D3D11_TESSELLATOR_OUTPUT_TRIANGLE_CCW: D3D_TESSELLATOR_OUTPUT_PRIMITIVE =
    D3D_TESSELLATOR_OUTPUT_PRIMITIVE::TRIANGLE_CCW;

#[repr(C)]
pub enum D3D_TESSELLATOR_PARTITIONING {
    UNDEFINED = 0,
    INTEGER = 1,
    POW2 = 2,
    FRACTIONAL_ODD = 3,
    FRACTIONAL_EVEN = 4,
}
pub const D3D11_TESSELLATOR_PARTITIONING_UNDEFINED: D3D_TESSELLATOR_PARTITIONING =
    D3D_TESSELLATOR_PARTITIONING::UNDEFINED;
pub const D3D11_TESSELLATOR_PARTITIONING_INTEGER: D3D_TESSELLATOR_PARTITIONING =
    D3D_TESSELLATOR_PARTITIONING::INTEGER;
pub const D3D11_TESSELLATOR_PARTITIONING_POW2: D3D_TESSELLATOR_PARTITIONING =
    D3D_TESSELLATOR_PARTITIONING::POW2;
pub const D3D11_TESSELLATOR_PARTITIONING_FRACTIONAL_ODD: D3D_TESSELLATOR_PARTITIONING =
    D3D_TESSELLATOR_PARTITIONING::FRACTIONAL_ODD;
pub const D3D11_TESSELLATOR_PARTITIONING_FRACTIONAL_EVEN: D3D_TESSELLATOR_PARTITIONING =
    D3D_TESSELLATOR_PARTITIONING::FRACTIONAL_EVEN;
